//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ans.Net10.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ans.Net10.Common.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;Понедельник;Вторник;Среда;Четверг;Пятница;Суббота;Воскресенье.
        /// </summary>
        public static string Array_DaysOfWeek {
            get {
                return ResourceManager.GetString("Array_DaysOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;Пн;Вт;Ср;Чт;Пт;Сб;Вс.
        /// </summary>
        public static string Array_DaysOfWeek2 {
            get {
                return ResourceManager.GetString("Array_DaysOfWeek2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;Пон;Вто;Сре;Чет;Пят;Суб;Вос.
        /// </summary>
        public static string Array_DaysOfWeek3 {
            get {
                return ResourceManager.GetString("Array_DaysOfWeek3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;января;февраля;марта;апреля;мая;июня;июля;августа;сентября;октября;ноября;декабря.
        /// </summary>
        public static string Array_Months {
            get {
                return ResourceManager.GetString("Array_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;янв;фев;мар;апр;мая;июн;июл;авг;сен;окт;ноя;дек.
        /// </summary>
        public static string Array_Months2 {
            get {
                return ResourceManager.GetString("Array_Months2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %d.
        /// </summary>
        public static string Format_Date_Day {
            get {
                return ResourceManager.GetString("Format_Date_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d MMMM.
        /// </summary>
        public static string Format_Date_DayAndMonth {
            get {
                return ResourceManager.GetString("Format_Date_DayAndMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d MMMM yyyy.
        /// </summary>
        public static string Format_Date_Full {
            get {
                return ResourceManager.GetString("Format_Date_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;сегодня&apos;.
        /// </summary>
        public static string Format_Date_Today {
            get {
                return ResourceManager.GetString("Format_Date_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;завтра&apos;.
        /// </summary>
        public static string Format_Date_Tomorrow {
            get {
                return ResourceManager.GetString("Format_Date_Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;вчера&apos;.
        /// </summary>
        public static string Format_Date_Yesterday {
            get {
                return ResourceManager.GetString("Format_Date_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d MMMM&apos; в &apos;H:mmmm.
        /// </summary>
        public static string Format_DateTime_DayAndMonth {
            get {
                return ResourceManager.GetString("Format_DateTime_DayAndMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d MMMM yyyy&apos; в &apos;H:mmmm.
        /// </summary>
        public static string Format_DateTime_Full {
            get {
                return ResourceManager.GetString("Format_DateTime_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;сегодня в &apos;H:mmmm.
        /// </summary>
        public static string Format_DateTime_Today {
            get {
                return ResourceManager.GetString("Format_DateTime_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;завтра в &apos;H:mmmm.
        /// </summary>
        public static string Format_DateTime_Tomorrow {
            get {
                return ResourceManager.GetString("Format_DateTime_Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;вчера в &apos;H:mmmm.
        /// </summary>
        public static string Format_DateTime_Yesterday {
            get {
                return ResourceManager.GetString("Format_DateTime_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### ### ### ###&apos; КБ&apos;.
        /// </summary>
        public static string Format_LengthKB {
            get {
                return ResourceManager.GetString("Format_LengthKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1=январь;2=февраль;3=март;4=апрель;5=май;6=июнь;7=июль;8=август;9=сентябрь;10=октябрь;11=ноябрь;12=декабрь;0=нет.
        /// </summary>
        public static string Registry_Months {
            get {
                return ResourceManager.GetString("Registry_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1=янв;2=фев;3=мар;4=апр;5=май;6=июн;7=июл;8=авг;9=сен;10=окт;11=ноя;12=дек;0=нет.
        /// </summary>
        public static string Registry_Months2 {
            get {
                return ResourceManager.GetString("Registry_Months2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создано: {0}.
        /// </summary>
        public static string Template_DataCreate {
            get {
                return ResourceManager.GetString("Template_DataCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновлено: {0}.
        /// </summary>
        public static string Template_DataUpdate {
            get {
                return ResourceManager.GetString("Template_DataUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вышестоящий {0} (в структуре).
        /// </summary>
        public static string Template_ParentPtr {
            get {
                return ResourceManager.GetString("Template_ParentPtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to –все–.
        /// </summary>
        public static string Text_AllItems {
            get {
                return ResourceManager.GetString("Text_AllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to –нет–.
        /// </summary>
        public static string Text_EmptyItem {
            get {
                return ResourceManager.GetString("Text_EmptyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to никогда.
        /// </summary>
        public static string Text_Never {
            get {
                return ResourceManager.GetString("Text_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите любую клавишу для выхода.
        /// </summary>
        public static string Text_PressAnyKeyToExit {
            get {
                return ResourceManager.GetString("Text_PressAnyKeyToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите ESC для выхода.
        /// </summary>
        public static string Text_PressEscToExit {
            get {
                return ResourceManager.GetString("Text_PressEscToExit", resourceCulture);
            }
        }
    }
}
