<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Reference Include="Ans.Net10.Common">
	    <HintPath>..\..\Ans.Net10.Common\bin\Debug\net10.0\Ans.Net10.Common.dll</HintPath>
	  </Reference>
	</ItemGroup>
	
</Project>