<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>

		<!--<GenerateDocumentationFile>True</GenerateDocumentationFile>-->

		<Version>10.1.0</Version>
		<VersionPrefix>$(Version)</VersionPrefix>
		<Authors>Roman Koff</Authors>
		<Copyright>$(Authors)</Copyright>
		<NeutralLanguage>ru</NeutralLanguage>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CsvHelper" Version="33.1.0" />
		<PackageReference Include="MailKit" Version="4.17.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Resources\Common.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Common.resx</DependentUpon>
		</Compile>
		<Compile Update="Resources\Exceptions.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Exceptions.resx</DependentUpon>
		</Compile>
		<Compile Update="Resources\Faces.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Faces.resx</DependentUpon>
		</Compile>
		<Compile Update="Resources\Form.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Form.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources\Common.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Common.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Exceptions.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Exceptions.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Faces.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Faces.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources\Form.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Form.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>
